### ISSUE TITLE
Warning after Tune Cocoapod is installed

### ISSUE THREAD

**Issue by jameshartt** [TuneOSS/cocoapod2.0#1]
Hi there,

Have been asked to install Tune on an app I'm working in, but am getting a warning upon compilation.

I am using the Cocoapod you have provided.

The project has recently, painstakingly, been brought down to zero warnings...! 😛

Your warning goes along the lines of...

while processing /Users/[redacted]/[redacted]/Pods/Tune/Tune.framework/Tune(TuneAnalyticsDispatchToConnectedModeOperation.o):
warning: /var/folders/p5/zjbm8q3549x0wpw_zn8wdxxr0000gn/C/com.apple.DeveloperTools/7.3-7D175/Xcode/7.3-7D175/Xcode/SharedPrecompiledHeaders/Tune-Prefix-bwbgbbzwplskghcyimcfyzqcljlz/Tune-Prefix.pch.pch: No such file or directory

Could you please resolve this?

Thanks in advance. 😄

**Comment by harshal-hasoffers** [comment]
Thanks for reporting the issue. We will let you know as soon as this is fixed.

**Comment by jameshartt** [comment]
It would normally be surpressed if it weren't in the precompiled header.

**Comment by jameshartt** [comment]
I am using the cocoa pods beta 1.0.0.beta.8

**Comment by harshal-hasoffers** [comment]
Attached here is a custom SDK built by disabling "Enable Clang Module Debugging" Xcode project setting:
[Tune.framework.zip](https://github.com/MobileAppTracking/cocoapod2.0/files/229052/Tune.framework.zip)

To test this framework thru Cocoapods, you may need to download and unzip the latest repo zip and replace the Tune.framework with the file attached here.
_Repo:_ https://github.com/MobileAppTracking/cocoapod2.0

You can temporarily modify the Podfile to source the Tune cocoapod locally:
pod 'Tune', :path => "path/to/unzipped/repo/folder"

It would be great if you can confirm if this solution works for you.

**Comment by jameshartt** [comment]
Hi @harshal-hasoffers, thank you very much for your help, warning free!! ⚠️ 🚫

Any idea when you'll be pushing out a new version of the library?

**Comment by harshal-hasoffers** [comment]
Thanks for confirming. I will include this fix in the upcoming release, which should hopefully go out next week. I will let you know once it is live.

**Comment by harshal-hasoffers** [comment]
@jameshartt The warning should be fixed by the latest released v4.2.1. Can you kindly confirm whenever you upgrade the SDK?

**Comment by S2Ler** [comment]
Warning gone in 4.2.1

**Comment by harshal-hasoffers** [comment]
@diejmon Thanks for the confirmation!

**Comment by jameshartt** [comment]
Yep, warning is all gone. Thanks for your effort :-)

**Comment by harshal-hasoffers** [comment]
@jameshartt Thanks!
