### ISSUE TITLE
Odd import directory structure

### ISSUE THREAD

**Issue by evilDave** [TuneOSS/cocoapod2.0#3]
The pod / framework is configured in such a way that I find I need to do:

`#import <Tune/Tune/Tune.h>`

in order for it to work, where I expect to be able to do:

`#import <Tune/Tune.h>`

indeed, that is what your documentation specifies.

The header file for me is found in:

`[my_source_dir]/Pods/Headers/Public/Tune/Tune/Tune.h`

**Comment by harshal-hasoffers** [comment]
@evilDave Any of the following `import` statements should work:
- `@import Tune;`
- `#import <Tune/Tune.h>`
- `#import <Tune/Tune/Tune.h>`

Please Note that the file items in `[my_source_dir]/Pods/Headers/Public/Tune/Tune/*.h` are just aliases to the actual header files located under `[my_source_dir]/Pods/Tune/Tune.framework/Headers/*.h`

**Result of: `ls -al Pods/Headers/Public/Tune/Tune/*.h`**

```
Pods/Headers/Public/Tune/Tune/Tune.h -> ../../../../Tune/Tune.framework/Headers/Tune.h
Pods/Headers/Public/Tune/Tune/TuneConstants.h -> ../../../../Tune/Tune.framework/Headers/TuneConstants.h
Pods/Headers/Public/Tune/Tune/TuneDebugUtilities.h -> ../../../../Tune/Tune.framework/Headers/TuneDebugUtilities.h
Pods/Headers/Public/Tune/Tune/TuneEvent.h -> ../../../../Tune/Tune.framework/Headers/TuneEvent.h
Pods/Headers/Public/Tune/Tune/TuneEventItem.h -> ../../../../Tune/Tune.framework/Headers/TuneEventItem.h
Pods/Headers/Public/Tune/Tune/TuneExperimentDetails.h -> ../../../../Tune/Tune.framework/Headers/TuneExperimentDetails.h
Pods/Headers/Public/Tune/Tune/TuneInAppMessageExperimentDetails.h -> ../../../../Tune/Tune.framework/Headers/TuneInAppMessageExperimentDetails.h
Pods/Headers/Public/Tune/Tune/TuneLocation.h -> ../../../../Tune/Tune.framework/Headers/TuneLocation.h
Pods/Headers/Public/Tune/Tune/TunePowerHookExperimentDetails.h -> ../../../../Tune/Tune.framework/Headers/TunePowerHookExperimentDetails.h
Pods/Headers/Public/Tune/Tune/TunePreloadData.h -> ../../../../Tune/Tune.framework/Headers/TunePreloadData.h
Pods/Headers/Public/Tune/Tune/TunePushInfo.h -> ../../../../Tune/Tune.framework/Headers/TunePushInfo.h
Pods/Headers/Public/Tune/Tune/UIViewController+NameTag.h -> ../../../../Tune/Tune.framework/Headers/UIViewController+NameTag.h
```

Here is a screenshot of the iOS+Cocoapods project folder structure:

![sample_ios_project_folder_structure_with_cocoapods](https://cloud.githubusercontent.com/assets/2146296/19289793/4c52a7c6-8fc1-11e6-998c-744ff7e96774.png)
