### ISSUE TITLE
Cannot use Tune as a pod dependency

### ISSUE THREAD

**Issue by vinceis1337** [TuneOSS/cocoapod2.0#4]
We're receiving this error when attempting to use Tune in a custom pod:

[!] The 'Pods-RMNTune_Example' target has transitive dependencies that include static binaries: (..../Pods/Tune/Tune.framework)

Is there any way we could receive a dynamically linked framework instead?

**Comment by ernesttune** [comment]
Hi Vinceis1337,

We have a ticket for this issue, I'll update you once we have a timeline figured out.

Thanks,
Ernest

**Comment by ernesttune** [comment]
Issue should be fixed in 5.0.0+
