### ISSUE TITLE
UserNotifications framework not available on iOS 9

### ISSUE THREAD

**Issue by vinceis1337** [TuneOSS/cocoapod2.0#6]
I noticed that your next version of Tune will include UserNotifications as a linked framework. I wanted to let you know that this compiles successfully but results in a fatal crash on launch when using iOS 9 devices.

dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications{{  }}

**Comment by ernesttune** [comment]
Thanks for the heads up!

**Comment by ernesttune** [comment]
I've been unsuccessful in reproducing the potential issue on an iOS 9 device.  Could you tell me what version of Xcode and the device model/OS version?

**Comment by vinceis1337** [comment]
@ernesttune I'm contacting our quality engineers for more information and I'll try to build you an example project ASAP!

**Comment by vinceis1337** [comment]
@ernesttune I think I may have been mistaken, I now believe this occurred due to a separate pod requiring linking to UserNotifications.
