### ISSUE TITLE
duplicate symbol _kReachabilityChangedNotification

### ISSUE THREAD

**Issue by domenicovoto** [TuneOSS/cocoapod2.0#7]
linker command failed -1 apple mach -0

duplicate symbol _kReachabilityChangedNotification
Tune.framework/Tune(SWReachability.o)

**Comment by ernesttune** [comment]
Thanks for the heads up!

Seems the reachability constant was not prefixed.  Working on a fix.

**Comment by ernesttune** [comment]
4.13.3 contains a fix for the duplicate symbol bug!
