### ISSUE TITLE
Tune.measure and Tune.initialize can crash if executed simulataneously

### ISSUE THREAD

**Issue by vinceis1337** [TuneOSS/cocoapod2.0#8]
Based on our internal investigations, it appears that if a two threads call either Tune.initialize or Tune.measure (or any combination of both) the SDK can fatally crash.

In the case of the initialization, it makes sense for us to block calls until it completes. However, since various actions can trigger the measure function (simultaneously even), I think that perhaps the Tune.measure call should have some sort of queue for processing received TuneEvents.

I don't have visibility into the SDK but let me know if I can provide any further information

**Comment by john-gu** [comment]
Hi @vinceis1337, we will create a ticket to look into this issue.

For reference, our SDK source code can be found here:
https://github.com/tuneoss/sdk-release

If you find any potential causes, please feel free to open a ticket there or update this issue.

Thanks!
