### ISSUE TITLE
Crash on iOS 9

### ISSUE THREAD

**Issue by bz569** [TuneOSS/cocoapod2.0#9]
In the `Tune.podspec`,   `s.ios.deployment_target` is set to `8.0`, and there is `UserNotifications` in `s.ios.frameworks`, which is only available on iOS 10+. When running on iOS 9, it would cause a crash.

**Comment by ernesttune** [comment]
Hey,  Thanks for the heads up!  We'll work on fixing this next week.

**Comment by ernesttune** [comment]
Issue should be fixed in 5.0.1
